/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa2023.OthelloGameImplementation;

import it.unicam.cs.pa2023.boardGamesLibrary.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public class AppOthello {

    public static void main(String[] args) {
        OthelloGame othelloGame = new OthelloGame();
        othelloGame.playGame();
    }

}

//codici unicode per pedine
//9898
//9899

//sequenza gioco: c,4 - c,3 - f,5