/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa2023.OthelloGameImplementation;

public class AppOthello {

    public static void main(String[] args) {
        OthelloGame othelloGame = new OthelloGame();
        othelloGame.playGame();

    }

}