/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa2023.OthelloGameImplementation;

import it.unicam.cs.pa2023.boardGamesLibrary.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public class AppOthello {

    public static void main(String[] args) {
        ArrayList<OthelloRule> othelloRules = new ArrayList<>();
        ArrayList<OthelloPlayer> othelloPlayers = new ArrayList<>();
        OthelloBoard othelloBoard = new OthelloBoard(8,8,1);
        OthelloGame othelloGame = new OthelloGame(othelloRules, othelloPlayers, "Othello", othelloBoard);
        othelloGame.playGame(othelloPlayers.get(0));
    }

}
